// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbNpmznWoJ485UAuR5G-fMhlJVxGnNQiw',
    appId: '1:1815264503:web:7ebe11f76aa648180667f2',
    messagingSenderId: '1815264503',
    projectId: 'flutter-fb-clean',
    authDomain: 'flutter-fb-clean.firebaseapp.com',
    storageBucket: 'flutter-fb-clean.appspot.com',
    measurementId: 'G-6KH8M1JH0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiugY6B2D2jvOHkIQZj5vLvQtgPt2kvg',
    appId: '1:1815264503:android:5521e59aba9fa1ca0667f2',
    messagingSenderId: '1815264503',
    projectId: 'flutter-fb-clean',
    storageBucket: 'flutter-fb-clean.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHrgmGFd_lCpKN5W_xCKp0OHpzvuGmMQ',
    appId: '1:1815264503:ios:955b9e0c344c09390667f2',
    messagingSenderId: '1815264503',
    projectId: 'flutter-fb-clean',
    storageBucket: 'flutter-fb-clean.appspot.com',
    iosClientId: '1815264503-561pnj040na0jehoekc7d4analdibbh2.apps.googleusercontent.com',
    iosBundleId: 'com.funkibitto',
  );
}
