name: flutter_fb_clean_architecture
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  alice: ^0.2.5
  flutter_modular: ^4.5.0
  flutter_triple: ^1.2.7+2
  freezed_annotation: 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_flavorizr: ^2.1.2
  injectable_generator: ^1.5.3 
  build_runner: any
  freezed: any




flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Dev App"

      android:
        applicationId: "com.funkibitto.flutter_fb_clean.dev"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "com.funkibitto.flutter_fb_clean.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "Prod App"

      android:
        applicationId: "com.funkibitto.flutter_fb_clean"
        firebase:
          config: ".firebase/prod/google-services.json"

      ios:
        bundleId: "com.funkibitto.flutter_fb_clean"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"


flutter:
  uses-material-design: true