// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9TUIUgbKxWjfCrYAVqA4La44Vmud-3O4',
    appId: '1:407405332541:web:130b2b1001f20fa0b00254',
    messagingSenderId: '407405332541',
    projectId: 'flutter-fb-clean-dev',
    authDomain: 'flutter-fb-clean-dev.firebaseapp.com',
    storageBucket: 'flutter-fb-clean-dev.appspot.com',
    measurementId: 'G-88PEX05F91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMfg_8HaWGJ2NdG3p4op_0h1It_ZhJXI',
    appId: '1:407405332541:android:0111d36cc88b4ad3b00254',
    messagingSenderId: '407405332541',
    projectId: 'flutter-fb-clean-dev',
    storageBucket: 'flutter-fb-clean-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-CJvHqOyYmR87uJgywNpRfKOQdxq3iIs',
    appId: '1:407405332541:ios:2a19db98b8d0e4f5b00254',
    messagingSenderId: '407405332541',
    projectId: 'flutter-fb-clean-dev',
    storageBucket: 'flutter-fb-clean-dev.appspot.com',
    iosClientId: '407405332541-vc7a6m4cpn1hvi82h6b886k3murn0r4o.apps.googleusercontent.com',
    iosBundleId: 'com.funkibitto',
  );
}
